var SITE_CONTENT = {
  "hero-eyebrow": "Boda Carve — verkstad för prototyper i trä",
  "hero-h1": "Boda Carve är en liten CNC-verkstad som tar sig an dubbelkrökta ytor, tunna gods och geometri som är svårförklarad",
  "hero-manifest": "Vi räknar inte kvadratmeter utan antalet försök som krävs för att lyckas.",
  "hero-lead": "Vi arbetar gärna med konstnärer, formgivare och arkitekter — oftast från en skiss, sällan från en färdig fil.",
  "avgransning-eyebrow": "Avgränsning",
  "avgransning-h2": "Vad vi tar oss an — och vad vi inte gör",
  "citat-text": "Toleransen är sällan det svåra. Det svåra är att veta vad ytan ska göra med ljuset.",
  "uppdrag-eyebrow": "Ett uppdrag",
  "uppdrag-h2": "Nationalpark som relief — från skiss till provbit",
  "uppdrag-intro": "Beställaren ville ha en nationalpark utformad som en relief i trä. Ingen fil, inga mått. Ytan var dubbelkrökt och godset skulle ner till åtta millimeter på det tunnaste stället.",
  "portfolio-eyebrow": "Portfolio",
  "portfolio-h2": "Fler uppdrag",
  "maskin-eyebrow": "Maskin & material",
  "omoss-eyebrow": "Om oss",
  "omoss-h2": "En verkstad, ett par händer och maskininlärning",
  "omoss-lead": "Boda Carve är litet med avsikt. Vi tar ett fåtal uppdrag åt gången eftersom den sortens arbete sällan går att köra parallellt — en unik form kräver ofta att vi står kvar vid maskinen och granskar CNC-banorna.",
  "omoss-muted": "Vi kommer från tillverkning av plastskuplturer på internationell nivå men Boda Carve jobbar enbar med trä och metall. Vi har en ambitiöst miljöinriktning och har lärt oss CNC för att kunna göra det som inte gick för hand. Du bestämmer formen, vi utför den.",
  "kontakt-eyebrow": "Kontakt",
  "kontakt-h2": "Skicka skissen. Även om den är på en servett.",
  "kontakt-muted": "Berätta vad du vill göra och vad du är osäker på. Vi återkommer med en bedömning av vad som är svårt, ungefär hur lång tid det tar och om vi är rätt verkstad för det.",
  "kontakt-meta": "      Boda Carve\n      Verkstad i Boda, Näshulta.\n      Besök efter överenskommelse\n    ",
  "footer-text": "  © 2026 Boda Carve",
  "avgransning-nej-1": "Stora serier till byggjättar",
  "uppdrag-steg1-p": "Topografin analyserades och kurvorna byggdes från grunden, så att ytan blev fräsbar utan att tappa sin karaktär.",
  "uppdrag-steg2-p": "Lanskapet var korrekt men lutade. Fel var inte geometrin utan uppspänningen eftersom reliefen kräver en mycket plan botten. ",
  "uppdrag-steg3-h3": "Limfogskiva via planfräsning",
  "uppdrag-steg3-p": "Timmar av arbete för att hitta rätt trä, på rätt plats för att göra topografin rättvis.",
  "uppdrag-steg4-h3": "Andra provbiten",
  "uppdrag-steg5-p": " Tiden gick åt till att lista ut hur, inte till att köra maskinen."
};
